### ISSUE TITLE
Writing gimie output to file instead of shell not consistent

### ISSUE THREAD

**Issue by rmfranken** [SDSC-ORD/gimie#49]
Using 
```
PS C:\Users\franken\PycharmProjects\rdf_tools> gimie data https://github.com/numpy/numpy > file.ttl
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\franken\AppData\Roaming\Python\Python311\Scripts\gimie.exe\__main__.py", line 7, in <module>
    sys.exit(app())
             ^^^^^

  File "C:\Users\franken\AppData\Roaming\Python\Python311\site-packages\gimie\cli.py", line 63, in data
    print(proj.serialize(format=format))

  File "C:\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

UnicodeEncodeError: 'charmap' codec can't encode characters in position 10433-10434: character maps to <undefined>



```

returns a unicode decode error (when I probe numpy github) However, if I put gimie repo as the repository to scrape, it works no problem. I don't understand why the difference between the two repos could cause a character encoding error.

**Comment by cmdoret** [comment]
This probably happens because there are unicode (e.g. russian, japanese) characters in some names and the windows console apparently does not support them by default. Does this solve your problem? https://stackoverflow.com/a/32176732/8440675
